import os
#modelsimpath = ['/cad/modelsim/modeltech/gcc-4.0.2-rhe21/bin']
env = Environment(ENV = {'PATH' : os.environ['PATH']})

env.Append(CPPPATH = './src/:./include:../pthreadUtils/include:../GnuPthUtils/include')

VariantDir('objPthreads','src',duplicate=0)
env.SharedLibrary('lib/libPipeHandler', ['objPthreads/pipeHandler.c','objPthreads/Pipes.c'], CCFLAGS='-O2 -DNDEBUG')
#env.SharedLibrary('lib/libPipeHandler', ['objPthreads/pipeHandler.c','objPthreads/Pipes.c'], CCFLAGS='-g -DDEBUG')

VariantDir('objGnuPth','src',duplicate=0)
env.SharedLibrary('lib/libPipeHandlerGnuPth', ['objGnuPth/pipeHandler.c','objGnuPth/Pipes.c'], CCFLAGS='-O2 -DNDEBUG -DUSE_GNUPTH')


VariantDir('objDebug','src',duplicate=0)
env.SharedLibrary('lib/libPipeHandlerDebug', ['objDebug/pipeHandler.c','objDebug/Pipes.c'], CCFLAGS='-g -DNDEBUG')



