#ifndef _AA_2_C__
#define _AA_2_C_

#include <stdint.h>

// this file will be autogenerated..
typedef uint8_t uint_8;
typedef uint16_t uint_16;
typedef uint32_t uint_32;
typedef uint64_t uint_64;

typedef int8_t int_8;
typedef int16_t int_16;
typedef int32_t int_32;
typedef int64_t int_64;

typedef float float_8_23;
typedef double float_11_52;

#endif
