
Import('env')

source_files = Glob('*.cpp')
env.Append(all_sources = Glob('*.[hc]pp'))

local = env.Clone()

local.Program('cdfg2dot', source_files)

local.AppendUnique(LIBS = ['CDFG', 'Base'])
local.AppendUnique(LIBPATH = ['#/lib/Base', '#/lib/CDFG'])
