import os
lower_dirs = Split('lib tools')

lower_scripts = map(lambda x : x + '/SConscript', lower_dirs)

env = Environment(ENV = os.environ)
env.ParseConfig("/usr/bin/pkg-config --cflags --libs libxml++-2.6")

conf = Configure(env)
if not conf.CheckLib('boost_program_options-mt'):
    if not conf.CheckLib('boost_program_options'):
        Exit(1)

if not conf.CheckLib('boost_serialization-mt'):
    if not conf.CheckLib('boost_serialization'):
        Exit(1)
env = conf.Finish()

env.MergeFlags('-I#/lib -ggdb')

Export('env')

SConscript(lower_scripts)

env.Command('TAGS', env['all_sources'], "etags $SOURCES")
