import os
#modelsimpath = ['/cad/modelsim/modeltech/gcc-4.0.2-rhe21/bin']
env = Environment(ENV = {'PATH' : os.environ['PATH']})
env.Append(CPPPATH = './src/:./include:../BitVectors/include:../CtestBench/include:../pipeHandler/include:../GnuPthUtils/include:../pthreadUtils/include:')

env.SharedLibrary('./lib/libRtl2AaMatcher', Glob('src/*.c'), CCFLAGS='-g ')

VariantDir('objDebug','src',duplicate=0)
env.SharedLibrary('./lib/libRtl2AaMatcherDebug', Glob('objDebug/*.c'), CCFLAGS='-g -DDEBUG ')

env.Program('bin/Rtl2AaMatcherTest', 'util/testRtl2AaMatcher.c', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['Rtl2AaMatcher', 'PipeHandlerDebugPthreads', 'BitVectors' , 'pthread', 'SockPipes' ],  LIBPATH=Split('./lib ../BitVectors/lib ../CtestBench/lib/ ../pipeHandler/lib/ '))


