import os
#modelsimpath = ['/cad/modelsim/modeltech/gcc-4.0.2-rhe21/bin']
env = Environment(ENV = {'PATH' : os.environ['PATH']})
AHIR_RELEASE=os.environ['AHIR_RELEASE']

env.Append(CPPPATH = './src/:./include:' + AHIR_RELEASE + '/include:')

env.SharedLibrary('./lib/libRtl2AaMatcher', Glob('src/*.c'), CCFLAGS='-g ')

VariantDir('objGnuPth','src',duplicate=0)
env.SharedLibrary('./lib/libRtl2AaMatcherGnuPth', Glob('objGnuPth/*.c'), CCFLAGS='-g -DUSE_GNUPTH ')

VariantDir('objDebug','src',duplicate=0)
env.SharedLibrary('./lib/libRtl2AaMatcherDebug', Glob('objDebug/*.c'), CCFLAGS='-g -DDEBUG ')

env.Program('bin/Rtl2AaMatcherTest', 'util/testRtl2AaMatcher.c', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['Rtl2AaMatcher', 'PipeHandlerDebugPthreads', 'BitVectors' , 'pthread', 'SockPipes' ], LIBPATH=Split('/usr/local/lib/ ' + AHIR_RELEASE + '/lib'))

VariantDir('utilGnuPth','util', duplicate=0)
env.Program('bin/Rtl2AaMatcherGnuPthTest', 'utilGnuPth/testRtl2AaMatcher.c', CCFLAGS='-g -DUSE_GNUPTH',LINKFLAGS='-g ', LIBS=['Rtl2AaMatcherGnuPth', 'PipeHandlerGnuPth', 'BitVectors' , 'pth', 'SockPipes' ], LIBPATH=Split('/usr/local/lib/ ' + AHIR_RELEASE + '/lib'))



