import os
#modelsimpath = ['/cad/modelsim/modeltech/gcc-4.0.2-rhe21/bin']
env = Environment(ENV = {'PATH' : os.environ['PATH']})

env.Append(CPPPATH = './src/:./include:../pthreadUtils/include:../GnuPthUtils/include:../BitVectors/include:../pipeHandler/include')

env.SharedLibrary('./lib/libRtl2AaMatcher', Glob('src/*.c'), CCFLAGS='-g ')

VariantDir('objGnuPth','src',duplicate=0)
env.SharedLibrary('./lib/libRtl2AaMatcherGnuPth', Glob('objGnuPth/*.c'), CCFLAGS='-g -DUSE_GNUPTH ')

VariantDir('objDebug','src',duplicate=0)
env.SharedLibrary('./lib/libRtl2AaMatcherDebug', Glob('objDebug/*.c'), CCFLAGS='-g -DDEBUG ')

env.Program('bin/Rtl2AaMatcherTest', 'util/testRtl2AaMatcher.c', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['Rtl2AaMatcher', 'PipeHandler', 'BitVectors' , 'pthread'], LIBPATH=Split('/usr/local/lib/ ./lib/ ../pipeHandler/lib/ ../BitVectors/lib/  '))

VariantDir('utilGnuPth','util', duplicate=0)
env.Program('bin/Rtl2AaMatcherGnuPthTest', 'utilGnuPth/testRtl2AaMatcher.c', CCFLAGS='-g -DUSE_GNUPTH',LINKFLAGS='-g ', LIBS=['Rtl2AaMatcherGnuPth', 'PipeHandlerGnuPth', 'BitVectors' , 'pth'], LIBPATH=Split('/usr/local/lib/ ./lib/ ../pipeHandler/lib/ ../BitVectors/lib/  '))



