
Import('env')

source_files = Glob('*.cpp')
env.Append(all_sources = Glob('*.[hc]pp'))

local = env.Clone()
local.ParseConfig('llvm-config --cxxflags --ldflags --libs core')

local.Program('vhdl-testgen', source_files)
local.AppendUnique(LIBS = ['Base'])
local.AppendUnique(LIBPATH = ['#/lib/Base'])

