import os
env = Environment(ENV = {'PATH' : os.environ['PATH']})

local = env.Clone()

local.ParseConfig('llvm-config --cxxflags --ldflags --libs bitreader bitwriter instrumentation scalaropts ipo')

VariantDir('obj','src',duplicate=0)
source_files = Glob('obj/*.cpp')

local.Append(CPPPATH = './include')
local.Program('bin/llvm2aa', source_files, CCFLAGS = '-g')

