float fpmul(float, float);
float fpincr(float);
float fpadd(float, float);
float fpsub(float, float);
float dotProduct(float x0, float y0, float x1, float y1, float x2, float y2, float x3, float y3);
uint8_t fpcmpgt(float x, float y);
uint8_t fpcmplt(float x, float y);
uint8_t fpcmpeq(float x, float y);
int32_t fp2int(float);
uint32_t fp2uint(double x);
double fpmuld (double x, double y);
double fpaddd (double x, double y);
double fpsubd (double x, double y);
int32_t fpd2int(double x);
uint32_t fpd2uint(double x);
float int2float(int32_t x);
double int2double(int32_t x);
