
Import('env')
local = env.Clone()

local.ParseConfig('llvm-config --cxxflags --ldflags --libs bitreader bitwriter instrumentation scalaropts ipo')

source_files = Glob('*.cpp')
env.Append(all_sources = Glob('*.[hc]pp'))

local.Program('llvm2cdfg', source_files)

local.AppendUnique(LIBS = ['Base', 'CDFG'])
local.AppendUnique(LIBPATH = ['#/lib/Base', '#/lib/CDFG'])
