import os
SConscript(['grammar/SConscript'])

env = Environment(ENV = {'PATH' : os.environ['PATH']})
ANTLR_PATH=os.environ['ANTLR_PATH']
ANTLR_LIB_PATH= ANTLR_PATH + '/lib/'
env.Append(CPPPATH = './src/:./include:' + ANTLR_PATH)

env.Library('lib/libHierSys', Glob('src/*.cpp'), CCFLAGS='-g ')
env.Program('bin/hierSys2Vhdl', 'util/hierSys2Vhdl.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['HierSys', 'antlr' ], LIBPATH=Split('/usr/local/lib/ ./lib/ ' + ANTLR_LIB_PATH))

