import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})
ANTLR_PATH=os.environ['ANTLR_PATH']
ANTLR_LIB_PATH=ANTLR_PATH + '/lib/'

SConscript(['grammar/SConscript'])
SConscript(['docs/SConscript'])

env.Append(CPPPATH = './src/:./include:./grammar/:../../Value/include:../../version/include:../../CtestBench/include:/usr/local/include/:')
env.Append(CPPPATH = ':../BGLWrap/include:' + ANTLR_PATH)

env.Library('lib/libAa', Glob('src/*.cpp'), CCFLAGS='-g ')
env.Program('bin/AaOpt', 'util/AaOpt.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['AhirVersion', 'Aa',  'Value', 'antlr'], LIBPATH=Split('/usr/local/lib/ ./lib/ ../../Value/lib/ ' + ' ../../version/lib/ ' + ANTLR_LIB_PATH))
env.Program('bin/Aa2VC', 'util/Aa2VC.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['AhirVersion', 'Aa',  'Value', 'antlr'], LIBPATH=Split('/usr/local/lib ./lib/ ../../Value/lib/ ' + ' ../../version/lib/ ' +  ANTLR_LIB_PATH))
env.Program('bin/Aa2C', 'util/Aa2C.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['AhirVersion', 'Aa',  'Value', 'antlr'], LIBPATH=Split('/usr/local/lib/ ./lib/ ../../Value/lib/ ' + ' ../../version/lib/ ' + ANTLR_LIB_PATH))
env.Program('bin/AaLinkExtMem', 'util/AaLinkExtMem.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['Aa', 'AhirVersion', 'Value', 'antlr'], LIBPATH=Split('/usr/local/lib/ ./lib/ ../../Value/lib/ ' + ' ../../version/lib/ ' +  ANTLR_LIB_PATH))
env.Program('bin/AaPreprocess', 'util/AaPreprocess.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBPATH=Split('/usr/local/lib'))




