import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})

SConscript(['grammar/SConscript'])

env.Append(CPPPATH = './src/:./include:../../../antlr2/:./grammar/:../../Value/include:/usr/local/boost_1_46_1/')
env.Library('lib/libAa', Glob('src/*.cpp'), CCFLAGS='-g ')
env.Program('bin/AaAnalyze', 'util/TestAaParser.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['Aa', 'antlr-4.0.3' , 'Value'], LIBPATH=Split('../../../antlr2/ ./lib/ ../../Value/lib/ '))
env.Program('bin/Aa2VC', 'util/Aa2VC.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['Aa', 'antlr-4.0.3' , 'Value'], LIBPATH=Split('../../../antlr2/ ./lib/ ../../Value/lib/'))
env.Program('bin/Aa2C', 'util/Aa2C.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['Aa', 'antlr-4.0.3' , 'Value'], LIBPATH=Split('../../../antlr2/ ./lib/ ../../Value/lib/'))
env.Program('bin/AaLinkExtMem', 'util/AaLinkExtMem.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['Aa', 'antlr-4.0.3' , 'Value'], LIBPATH=Split('../../../antlr2/ ./lib/ ../../Value/lib/'))




