import os
env = Environment(ENV = {'PATH' : os.environ['PATH']})
env.Append(CPPPATH = './src/:./include/')
env.Library('lib/libSizedIntegers', Glob('src/*.c'), CCFLAGS='-g ')
#env.Program('bin/TestValue','util/TestValue.cpp',CCFLAGS='-g',LINKFLAGS='-g', LIBS=['Value'], LIBPATH=['./lib'])





