import os
env = Environment(ENV = {'PATH' : os.environ['PATH']})
env.Append(CPPPATH = './src/:./include/')
env.Library('lib/libBitVectors', Glob('src/*.c'), CCFLAGS='-g ')
env.Program('bin/test_bit_vectors','util/test_bit_vectors.c',CCFLAGS='-g',LINKFLAGS='-g', LIBS=['BitVectors'], LIBPATH=['./lib'])





