import os
env = Environment(ENV = {'PATH' : os.environ['PATH']})

local = env.Clone()

local.ParseConfig('llvm-config --cxxflags --ldflags --libs bitreader bitwriter instrumentation scalaropts ipo')

source_files = Glob('*.cpp')
local.Append(all_sources = Glob('*.[hc]pp'))

local.Program('llvm2aa', source_files, CCFLAGS = '-g')

