import os
env = Environment(ENV = {'PATH' : os.environ['PATH']})
ANTLR_JAR=os.environ['ANTLR_JAR_PATH']
# use a path to get to the antlr jar "later"
# also: how does one force the action if the source has changed?
ant = Builder(action = 'java -cp ' + ANTLR_JAR + '/antlr.jar antlr.Tool  -o Ahir-asm/devel/src/ $SOURCE')
antdoc = Builder(action = 'java -cp ' + ANTLR_JAR +'/antlr.jar antlr.Tool -html -o Ahir-asm/devel/docs/ $SOURCE')
env.Prepend(BUILDERS = {'antlr' : ant})
env.Prepend(BUILDERS = {'antlrdocs' : antdoc})
env.antlr(['../src/AaLexer.hpp', '../src/AaParser.hpp', '../src/AaLexer.cpp','../src/AaParser.cpp', 'AaParserTokenTypes.hpp','AaParserTokenTypes.txt' ], 'Aa.g')
env.antlrdocs(['../docs/AaLexer.html', '../docs/AaParser.html'], 'Aa.g')
