import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})

# use a path to get to the antlr jar "later"
# also: how does one force the action if the source has changed?
ant = Builder(action = 'java -cp  ../Ahir-asm/antlr2/antlr.jar antlr.Tool -o src $SOURCE')

env.Prepend(BUILDERS = {'antlr' : ant})
env.Append(CPPPATH = './src/:./include:../Ahir-asm/antlr2/')

VariantDir('obj','src',duplicate=0)
env.antlr(['obj/vcLexer.cpp','obj/vcParser.cpp'], 'grammar/vc.g')
env.Object(Glob('obj/*.cpp'))




