#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <Pipes.h>
#include <SocketLib.h>
void foo();
void in_ctrl_module();
void in_data_module();
void out_ctrl_module();
void out_data_module();
