import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})

# use a path to get to the antlr jar "later"
# also: how does one force the action if the source has changed?
ant = Builder(action = 'java -cp  ../Ahir-asm/antlr2/antlr.jar antlr.Tool -o src $SOURCE')

env.Prepend(BUILDERS = {'antlr' : ant})
env.Append(CPPPATH = './src/:./include:../Ahir-asm/antlr2/')

VariantDir('obj','src',duplicate=0)
env.antlr(['obj/vcLexer.cpp','obj/vcParser.cpp'], 'grammar/vc.g')

# env.Object(Glob('obj/*.cpp'))
# env.Program('bin/vcParse', Glob('obj/*.cpp'),CCFLAGS='-g -DVCPARSE',LINKFLAGS='-g -DVCPARSE', LIBS=['antlr-4.0.3'], LIBPATH='../Ahir-asm/antlr2/')

env.Library('lib/libVC', Glob('obj/*.cpp'), CCFLAGS='-g ')
env.Program('bin/vcParse', 'util/vcParseMain.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['VC', 'antlr-4.0.3' ], LIBPATH=Split('../Ahir-asm/antlr2/ ./lib/'))
env.Program('bin/vcCPCheck', 'util/vcCPCheck.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['VC', 'antlr-4.0.3' ], LIBPATH=Split('../Ahir-asm/antlr2/ ./lib/'))
env.Program('bin/vcFormat', 'util/vcFormat.cpp',CCFLAGS='-g ', LINKFLAGS='-g ')
env.Program('bin/vhdlFormat', 'util/vhdlFormat.cpp',CCFLAGS='-g ', LINKFLAGS='-g ')
env.Program('bin/vc2vhdl', 'util/vc2vhdl.cpp', CCFLAGS='-g ',LINKFLAGS='-g ', LIBS=['VC', 'antlr-4.0.3' ], LIBPATH=Split('../Ahir-asm/antlr2/ ./lib/'))





