import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})

env.Append(CPPPATH = './src/:./include')


VariantDir('obj','src',duplicate=0)
env.Library('lib/libSocketLib', Glob('obj/*.c'), CCFLAGS='-g ')





