import os

env = Environment(ENV = {'PATH' : os.environ['PATH']})

env.Append(CPPPATH = './src/:./include:../socketlib/include')

VariantDir('obj','src',duplicate=0)

env.Library('lib/libVhpi', Glob('obj/*.c'), CCFLAGS='-g ')





