import os
env = Environment(ENV = {'PATH' : os.environ['PATH']})
# use a path to get to the antlr jar "later"
# also: how does one force the action if the source has changed?
ANTLR_JAR_PATH=os.environ['ANTLR_PATH'] + '/lib/'
ant = Builder(action = 'java -cp ' + ANTLR_JAR_PATH + '/antlr.jar antlr.Tool  -o HierSysBuild/src/ $SOURCE')
antdoc = Builder(action = 'java -cp ' + ANTLR_JAR_PATH + '/antlr.jar antlr.Tool -html -o HierSysBuild/docs/ $SOURCE')
env.Prepend(BUILDERS = {'antlr' : ant})
env.Prepend(BUILDERS = {'antlrdocs' : antdoc})
env.antlr(['../src/hierSysLexer.hpp', '../src/hierSysParser.hpp', '../src/hierSysLexer.cpp','../src/hierSysParser.cpp', 'hierSysParserTokenTypes.hpp','hierSysParserTokenTypes.txt' ], 'hierSys.g')
env.antlrdocs(['../docs/hierSysLexer.html', '../docs/hierSysParser.html'], 'hierSys.g')
