rm -f ahir.vhdl
rm -f ieee_proposed.vhdl
cat ../packagesV2/Types.vhd >> ahir.vhdl
cat ../packagesV2/Utilities.vhd >> ahir.vhdl
cat ../packagesV2/Subprograms.vhd >> ahir.vhdl
cat ../packagesV2/BaseComponents.vhd >> ahir.vhdl
cat ../packagesV2/Components.vhd >> ahir.vhdl
cat ../packagesV2/FloatOperatorPackage.vhd >> ahir.vhdl
cat ../packagesV2/OperatorPackage.vhd >> ahir.vhdl
cat ../memory_subsystem/mem_component_pack.vhd >> ahir.vhdl
cat ../memory_subsystem/mem_function_pack.vhd >> ahir.vhdl
cat ../memory_subsystem/memory_subsystem_package.vhd >> ahir.vhdl
cat ../memory_subsystem/merge_functions.vhd >> ahir.vhdl
cat ../memory_subsystem/base_bank.vhd >> ahir.vhdl
cat ../memory_subsystem/combinational_merge.vhd >> ahir.vhdl
cat ../memory_subsystem/demerge_tree.vhd >> ahir.vhdl
cat ../memory_subsystem/demerge_tree_wrap.vhd >> ahir.vhdl
cat ../memory_subsystem/dummy_read_only_memory_subsystem.vhd >> ahir.vhdl
cat ../memory_subsystem/dummy_write_only_memory_subsystem.vhd >> ahir.vhdl
cat ../memory_subsystem/mem_demux.vhd >> ahir.vhdl
cat ../memory_subsystem/memory_bank_base.vhd >> ahir.vhdl
cat ../memory_subsystem/memory_bank.vhd >> ahir.vhdl
cat ../memory_subsystem/memory_subsystem_core.vhd >> ahir.vhdl
cat ../memory_subsystem/memory_subsystem.vhd >> ahir.vhdl
cat ../memory_subsystem/mem_repeater.vhd >> ahir.vhdl
cat ../memory_subsystem/mem_shift_repeater.vhd >> ahir.vhdl
cat ../memory_subsystem/merge_box_with_repeater.vhd >> ahir.vhdl
cat ../memory_subsystem/merge_tree.vhd >> ahir.vhdl
cat ../memory_subsystem/register_bank.vhd >> ahir.vhdl
cat ../control-path/*.vhdl >> ahir.vhdl
cat ../operatorsV2/base/*.vhd >> ahir.vhdl
cat ../ieee_proposed/trimmed/math_utility_pkg.vhd >> ieee_proposed.vhdl
cat ../ieee_proposed/trimmed/fixed_float_types_c.vhdl >> ieee_proposed.vhdl
cat ../ieee_proposed/trimmed/fixed_pkg_c.vhd >> ieee_proposed.vhdl
cat ../ieee_proposed/trimmed/float_pkg_c.vhd >> ieee_proposed.vhdl
