rm -f ahirForAsic.vhdl
cat ../ahir/packagesV2/GlobalConstants.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/Types.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/Utilities.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/Subprograms.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/BaseComponents.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/Components.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/FloatOperatorPackage.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/OperatorPackage.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/mem_component_pack.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/mem_function_pack.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/memory_subsystem_package.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/merge_functions.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/functionLibraryComponents.vhd >> ahirForAsic.vhdl
cat ../ahir/packagesV2/ApIntComponents.vhd >> ahirForAsic.vhdl
cat ../ahir/memory_subsystem/common/*.vhd >> ahirForAsic.vhdl
cat ../ahir/memory_subsystem/base_bank_asic/*.vhd >> ahirForAsic.vhdl
cat ../ahir/memory_subsystem/strictly_ordered/*.vhd >> ahirForAsic.vhdl
cat ../ahir/memory_subsystem/unordered/*.vhd >> ahirForAsic.vhdl
cat ../ahir/control-path/*.vhdl >> ahirForAsic.vhdl
cat ../ahir/operatorsV2/base/*.vhd >> ahirForAsic.vhdl
cat ../ahir/operatorsV2/ieee754/*.vhd >> ahirForAsic.vhdl
cat ../ahir/operatorsV2/experimental/*.vhd >> ahirForAsic.vhdl
cat ../ahir/operatorsV2/glue/*.vhd >> ahirForAsic.vhdl
cat ../ahir/operatorsV2/functionLibrary/*.vhd >> ahirForAsic.vhdl
cat ../ahir/operatorsV2/ap_int/*.vhd >> ahirForAsic.vhdl
cat ../aHiR_ieee_proposed/trimmed/math_utility_pkg.vhd >> aHiR_ieee_proposed.vhdl
cat ../aHiR_ieee_proposed/trimmed/fixed_float_types_c.vhdl >> aHiR_ieee_proposed.vhdl
cat ../aHiR_ieee_proposed/trimmed/fixed_pkg_c.vhd >> aHiR_ieee_proposed.vhdl
cat ../aHiR_ieee_proposed/trimmed/float_pkg_c.vhd >> aHiR_ieee_proposed.vhdl
