rm -f ahirForImage.vhdl
cat ../ahir/packagesV2/Types.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/Utilities.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/Subprograms.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/BaseComponents.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/Components.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/FloatOperatorPackage.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/OperatorPackage.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/mem_component_pack.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/mem_function_pack.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/memory_subsystem_package.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/merge_functions.vhd >> ahirForImage.vhdl
cat ../ahir/packagesV2/functionLibraryComponents.vhd >> ahirForImage.vhdl
cat ../ahir/memory_subsystem/common/*.vhd >> ahirForImage.vhdl
cat ../ahir/memory_subsystem/base_bank_image/*.vhd >> ahirForImage.vhdl
cat ../ahir/memory_subsystem/strictly_ordered/*.vhd >> ahirForImage.vhdl
cat ../ahir/memory_subsystem/unordered/*.vhd >> ahirForImage.vhdl
cat ../ahir/control-path/*.vhdl >> ahirForImage.vhdl
cat ../ahir/operatorsV2/base/*.vhd >> ahirForImage.vhdl
cat ../ahir/operatorsV2/ieee754/*.vhd >> ahirForImage.vhdl
cat ../ahir/operatorsV2/experimental/*.vhd >> ahirForImage.vhdl
cat ../ahir/operatorsV2/functionLibrary/*.vhd >> ahirForImage.vhdl
